### ISSUE TITLE
SyncArbitrer actor using both SyncContext and ResponseFuture is panicking

### ISSUE THREAD

**Issue by bmoyet** [actix/actix#492]
Hi,

It seems I'm unable to have an actor in SyncArbitrer, whose Result is ResponseFuture.

## Expected Behavior

The program should print `println!("I've received : {}", msg);` twice

(Program can be found here : https://gist.github.com/bmoyet/828bfd2f55aabc64aab01294b982d90c)

## Current Behavior

Program is panicking: 

```
thread '<unnamed>' panicked at '`spawn_local` called from outside of a `task::LocalSet`', /home/bastien/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/task/local.rs:303:thread '18
<unnamed>' panicked at '`spawn_local` called from outside of a `task::LocalSet`', /home/bastien/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/task/local.rs:303:18stack backtrace:

stack backtrace:
   0: rust_begin_unwind
             at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/core/src/option.rs:1241:5
   3: core::option::Option<T>::expect
             at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/core/src/option.rs:349:21
   4: tokio::task::local::spawn_local::{{closure}}
             at /home/bastien/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/task/local.rs:302:22
   5: tokio::macros::scoped_tls::ScopedKey<T>::with
             at /home/bastien/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/macros/scoped_tls.rs:72:13
   6: tokio::task::local::spawn_local
             at /home/bastien/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/task/local.rs:301:9
   7: actix_rt::spawn
             at /home/bastien/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-2.2.0/src/lib.rs:167:5
   8: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future+Output = <M as actix::handler::Message>::Result>> as actix::handler::MessageResponse<A,M>>::handle
             at /home/bastien/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.11.1/src/handler.rs:383:9
   9: <actix::sync::SyncContextEnvelope<M> as actix::address::envelope::EnvelopeProxy<A>>::handle
             at /home/bastien/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.11.1/src/sync.rs:352:13
  10: <actix::address::envelope::Envelope<A> as actix::address::envelope::EnvelopeProxy<A>>::handle
             at /home/bastien/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.11.1/src/address/envelope.rs:53:9
  11: actix::sync::SyncContext<A>::run
             at /home/bastien/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.11.1/src/sync.rs:262:21
  12: actix::sync::SyncArbiter<A>::start::{{closure}}
             at /home/bastien/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.11.1/src/sync.rs:128:17

```

## Steps to Reproduce (for bugs)

You can find an example here : https://gist.github.com/bmoyet/828bfd2f55aabc64aab01294b982d90c

## Context

I need my multihreaded Actor to send a response back to the library I'm using. And obviously I must use an async channel to await the response and not block my whole program. However when doing so (SyncContext + ResponseFuture) the program panicks. 

At the moment I'm using a work around with a secondary not SyncContext actor which will send the response through the channel, but I'm not seeing any obvious reason why my primary actor cannot process and respond.

## Your Environment

* Rust Version (I.e, output of `rustc -V`): rustc 1.48.0 (7eac88abb 2020-11-16)
* Actix Version: 0.11.1

**Comment by fakeshadow** [comment]
Like `SyncArbitrer` and `SyncContext`'s name. They are for sync(or blocking) code only.
If you need async context please use `Arbiter` and `Context`.

**Comment by bmoyet** [comment]
Thanks for the answer, the naming should have ring a bell indeed :+1:
