### ISSUE TITLE
`#[actix::test]` passes even if actor panics

### ISSUE THREAD

**Issue by damszew** [actix/actix#494]
`#[actix::test]` passes even if actor panics. This is especially problematic when using [mockall](https://github.com/asomers/mockall).

## Expected Behavior
Both tests should be `FAILED`

## Current Behavior
```bash
❯ cargo t should_fail_on -- --nocapture

running 2 tests
thread 'tests::should_fail_on_panic' panicked at 'explicit panic', src/main.rs:59:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test tests::should_fail_on_panic ... FAILED
thread 'tests::should_fail_on_actor_panic' panicked at 'explicit panic', src/main.rs:59:9
test tests::should_fail_on_actor_panic ... ok

failures:
    tests::should_fail_on_panic

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

## Steps to Reproduce (for bugs)
```rust
use actix::prelude::*;

#[derive(Message)]
#[rtype(result = "Result<bool, std::io::Error>")]
struct Ping;

struct MyActor;

impl Actor for MyActor {
    type Context = Context<Self>;
}

impl Handler<Ping> for MyActor {
    type Result = Result<bool, std::io::Error>;

    fn handle(&mut self, _msg: Ping, _ctx: &mut Context<Self>) -> Self::Result {
        Ok(true)
    }
}

impl Drop for MyActor {
    fn drop(&mut self) {
        panic!();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[actix::test]
    async fn should_fail_on_actor_panic() {
        let addr = MyActor.start();
    }

    #[test]
    fn should_fail_on_panic() {
        let addr = MyActor;
    }
}
```

## Context

I'm using [mockall](https://github.com/asomers/mockall) to mock underlying IO operations and set expectations of what should be executed. **If I have expectation that some method will be called twice but my actor will call it only once -> test will pass.**

## Your Environment

* Rust Version (I.e, output of `rustc -V`): `rustc 1.51.0 (2fd73fabe 2021-03-23)`
* Actix Version: `0.11.1`

**Comment by fakeshadow** [comment]
With master branch one can do the following. 

```rust
use actix::prelude::*;
struct Act;

impl Actor for Act {
    type Context = Context<Self>;

    fn started(&mut self, ctx: &mut Self::Context) {
        ctx.stop();
    }
}

impl Drop for Act {
    fn drop(&mut self) {
        panic!("123")
    }
}

fn main() {}

#[test]
fn panic() {
    System::new().block_on(async {
        let ctx = Context::<Act>::new();

        let _addr = ctx.address();

        let actor = ctx.into_future(Act);

        actix_rt::spawn(async {
            let _ = actor.await;
        })
        .await
        .unwrap();
    })
}
```

**Comment by damszew** [comment]
Seems enough for my case. Thanks for help
