### ISSUE TITLE
How to send a message from an actor?

### ISSUE THREAD

**Issue by artemshein** [actix/actix#77]
I got this:
`thread 'main' panicked at 'Use Self::Context::notify() instead of direct use of address',`
when I try to send a message:
```
struct FragmentLoader {
    model_info_merger: Addr<Unsync, ModelInfoMergeController>
}

impl Actor for FragmentLoader {
    type Context = actix::Context<Self>;
}

impl Handler<LoadFragment> for FragmentLoader {
    type Result = ();

    fn handle(&mut self, mut msg: LoadFragment, ctx: &mut actix::Context<FragmentLoader>) -> Self::Result {
        // ...
        self.model_info_merger.do_send(MergeModelInfo { model_info: msg.model_info });
    }
}
```
How to send a message to another actor, not the Context < Self >?

**Comment by fafhrd91** [comment]
This is debug only panic. You send more than 256 messages at once. I will remove this panic in next version. But in general it is not good idea to send that much messages it is much faster to send vec or something like that

**Comment by artemshein** [comment]
I don't send 256 messages at once, I send messages one-by-one. It seems that the problem is -- these messages handler was never started. I'm trying to start an actor from inside of the other actor and immediately send it a message:
```
impl Handler<MergeModelInfo> for ModelInfoMergeController {
    type Result = ();

    fn handle(&mut self, msg: MergeModelInfo, ctx: &mut Self::Context) -> Self::Result {
        trace!("ModelInfoMergeController::handle {}", self.received_fragments);
        self.received_fragments += 1;
        match mem::replace(&mut self.model_info, None) {
            Some(model_info) => {
                // I also tried ModelInfoMerger.start() here
                let addr: Addr<Syn, _> = Arbiter::arbiter().send(msgs::StartActor::new(|_| ModelInfoMerger)).wait().unwrap();
                addr.do_send(MergeTwoModelInfos {
                    first: model_info,
                    second: msg.model_info
                });
            }
            _ => {}
        }
    }
}
```
Could it be the cause of this error?

**Comment by fafhrd91** [comment]
yes, that could cause this panic.

why do you need to start from inside the handler? can't you start it upfront?

**Comment by artemshein** [comment]
My task is to merge objects (lets say vectors) in parallel. My approach was to have an actor which receives two vectors and immediately spawns a merge actor for them, which just merges two vectors and sends result back to the original actor. So the process is kind of iterative.
Am I misusing the library? I thought that actors are very cheap and the docs say that one could spawn new actors in the process.

**Comment by artemshein** [comment]
Thanks for your answers. You are right.

**Comment by Boscop** [comment]
I'm also getting this panic:
```
set_hook: PANIC OCCURRED: Use Self::Context::notify() instead of direct use of address
LOCATION: C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-0.7.6\src\mailbox.rs:103
stack backtrace:
   0:     0x7ff6fa2d2667 - backtrace::backtrace::trace<closure>
                        at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.9\src\backtrace\mod.rs:42
   1:     0x7ff6fa2d1c83 - backtrace::capture::Backtrace::new
                        at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.9\src\capture.rs:63
   2:     0x7ff6f9dfee1e - myproject::panic_handler
                        at D:\projects\myproject\src\main.rs:280
   3:     0x7ff6f9dfed04 - myproject::register_panic_handler::{{closure}}
                        at D:\projects\myproject\src\main.rs:268
   4:     0x7ff6fa2ee765 - std::panicking::rust_panic_with_hook
                        at /rustc/00e03ee57446d47667e5adba77fca8c13bfe7535\/src\libstd\panicking.rs:483
   5:     0x7ff6fa294fbe - std::panicking::begin_panic<str*>
                        at \rustc\00e03ee57446d47667e5adba77fca8c13bfe7535\src\libstd\panicking.rs:410
   6:     0x7ff6fa0881dc - actix::mailbox::Mailbox<webui::act::WsChatSession>::poll<webui::act::WsChatSession>
                        at <::std::macros::panic macros>:3
   7:     0x7ff6fa0682a2 - actix::contextimpl::{{impl}}::poll<webui::act::WsChatSession,actix_web::ws::context::WebsocketContext<webui::act::WsChatSession, webui::act::WsChatSessionState>>
                        at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-0.7.6\src\contextimpl.rs:347
   8:     0x7ff6fa066cc3 - actix_web::ws::context::{{impl}}::poll<webui::act::WsChatSession,webui::act::WsChatSessionState>
                        at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-web-0.7.13\src\ws\context.rs:310
   9:     0x7ff6fa09a16b - actix_web::pipeline::ProcessResponse<webui::act::WsChatSessionState, actix_web::application::Inner<webui::act::WsChatSessionState>>::poll_io<webui::act::WsChatSessionState,actix_web::application::Inner<webui::act::WsChatSessionState>>
                        at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-web-0.7.13\src\pipeline.rs:627
  10:     0x7ff6fa098311 - actix_web::pipeline::{{impl}}::poll_io<webui::act::WsChatSessionState,actix_web::application::Inner<webui::act::WsChatSessionState>>
                        at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-web-0.7.13\src\pipeline.rs:127
  11:     0x7ff6fa07929e - actix_web::server::h1::Entry<actix_web::application::HttpApplication<webui::act::WsChatSessionState>>::poll_io<actix_web::application::HttpApplication<webui::act::WsChatSessionState>>
                        at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-web-0.7.13\src\server\h1.rs:75
  12:     0x7ff6fa07a1bf - actix_web::server::h1::Http1Dispatcher<tokio_tcp::stream::TcpStream, actix_web::application::HttpApplication<webui::act::WsChatSessionState>>::poll_handler<tokio_tcp::stream::TcpStream,actix_web::application::HttpApplication<webui::act::WsChatSessionState>>
                        at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-web-0.7.13\src\server\h1.rs:364
  13:     0x7ff6fa0b288e - actix_web::server::h1::Http1Dispatcher<tokio_tcp::stream::TcpStream, actix_web::application::HttpApplication<webui::act::WsChatSessionState>>::poll<tokio_tcp::stream::TcpStream,actix_web::application::HttpApplication<webui::act::WsChatSessionState>>

                        at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-web-0.7.13\src\server\h1.rs:208
  14:     0x7ff6fa0b1805 - actix_web::server::channel::{{impl}}::poll<tokio_tcp::stream::TcpStream,actix_web::application::HttpApplication<webui::act::WsChatSessionState>>
                        at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-web-0.7.13\src\server\channel.rs:105
  15:     0x7ff6fa0a2cc9 - actix_net::service::map_err::{{impl}}::poll<actix_web::server::service::HttpServiceHandler<actix_web::application::HttpApplication<webui::act::WsChatSessionState>, tokio_tcp::stream::TcpStream>,closure,()>
                        at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-net-0.1.1\src\service\map_err.rs:92
  16:     0x7ff6fa0a20e9 - actix_web::server::acceptor::{{impl}}::poll<actix_net::service::and_then::AndThen<actix_net::service::map_err::MapErr<actix_web::server::acceptor::TcpAcceptorService<actix_net::service::map_err::MapErr<actix_web::server::acceptor::DefaultAcceptor, fn(()) -> actix_web::server::error::AcceptorError<()>, actix_web::server::error::AcceptorError<()>>>, closure, ()>, actix_net::service::map_err::MapErr<actix_web::server::service::HttpServiceHandler<actix_web::application::HttpApplication<webui::act::WsChatSessionState>, tokio_tcp::stream::TcpStream>, closure, ()>>>
                        at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-web-0.7.13\src\server\acceptor.rs:378
  17:     0x7ff6fa0af67e - futures::future::map_err::{{impl}}::poll<(),futures::future::either::Either<futures::future::either::Either<actix_web::server::acceptor::ServerMessageAcceptorServiceFut<actix_net::service::and_then::AndThen<actix_net::service::map_err::MapErr<actix_web::server::acceptor::TcpAcceptorService<actix_net::service::map_err::MapErr<actix_web::server::acceptor::DefaultAcceptor, fn(()) -> actix_web::server::error::AcceptorError<()>, actix_web::server::error::AcceptorError<()>>>, closure, ()>, actix_net::service::map_err::MapErr<actix_web::server::service::HttpServiceHandler<actix_web::application::HttpApplication<webui::act::WsChatSessionState>, tokio_tcp::stream::TcpStream>, closure, ()>>>, futures::future::result_::FutureResult<(), ()>>, futures::future::either::Either<actix_web::server::acceptor::ServerMessageAcceptorServiceFut<actix_net::service::and_then::AndThen<actix_net::service::map_err::MapErr<actix_web::server::acceptor::TcpAcceptorService<actix_web::server::acceptor::AcceptorTimeoutService<actix_web::server::acceptor::DefaultAcceptor>>, closure, ()>, actix_net::service::map_err::MapErr<actix_web::server::service::HttpServiceHandler<actix_web::application::HttpApplication<webui::act::WsChatSessionState>, tokio_tcp::stream::TcpStream>, closure, ()>>>, futures::future::result_::FutureResult<(), ()>>>,closure>
                        at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.25\src\future\map_err.rs:30
  18:     0x7ff6fa0a188e - futures::future::map::{{impl}}::poll<(),futures::future::map_err::MapErr<futures::future::either::Either<futures::future::either::Either<actix_web::server::acceptor::ServerMessageAcceptorServiceFut<actix_net::service::and_then::AndThen<actix_net::service::map_err::MapErr<actix_web::server::acceptor::TcpAcceptorService<actix_net::service::map_err::MapErr<actix_web::server::acceptor::DefaultAcceptor, fn(()) -> actix_web::server::error::AcceptorError<()>, actix_web::server::error::AcceptorError<()>>>, closure, ()>, actix_net::service::map_err::MapErr<actix_web::server::service::HttpServiceHandler<actix_web::application::HttpApplication<webui::act::WsChatSessionState>, tokio_tcp::stream::TcpStream>, closure, ()>>>, futures::future::result_::FutureResult<(), ()>>, futures::future::either::Either<actix_web::server::acceptor::ServerMessageAcceptorServiceFut<actix_net::service::and_then::AndThen<actix_net::service::map_err::MapErr<actix_web::server::acceptor::TcpAcceptorService<actix_web::server::acceptor::AcceptorTimeoutService<actix_web::server::acceptor::DefaultAcceptor>>, closure, ()>, actix_net::service::map_err::MapErr<actix_web::server::service::HttpServiceHandler<actix_web::application::HttpApplication<webui::act::WsChatSessionState>, tokio_tcp::stream::TcpStream>, closure, ()>>>, futures::future::result_::FutureResult<(), ()>>>, closure>,closure>
                        at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.25\src\future\map.rs:30
  19:     0x7ff6fa1d40bc - futures::task_impl::std::set<closure,core::result::Result<futures::poll::Async<()>, ()>>
                        at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.25\src\task_impl\std\mod.rs:79
  20:     0x7ff6fa1ce533 - std::thread::local::LocalKey<tokio_current_thread::CurrentRunner>::with<tokio_current_thread::CurrentRunner,closure,bool>
                        at \rustc\00e03ee57446d47667e5adba77fca8c13bfe7535\src\libstd\thread\local.rs:255
  21:     0x7ff6fa1c7f7d - tokio_current_thread::scheduler::Scheduler<tokio_reactor::Handle>::tick<tokio_reactor::Handle>
                        at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-current-thread-0.1.3\src\scheduler.rs:333
  22:     0x7ff6fa1c4e06 - tokio_current_thread::Entered<tokio_timer::timer::Timer<tokio_reactor::Reactor, tokio_timer::clock::clock::Clock>>::block_on<tokio_timer::timer::Timer<tokio_reactor::Reactor, tokio_timer::clock::clock::Clock>,futures::sync::oneshot::Receiver<i32>>
                        at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-current-thread-0.1.3\src\lib.rs:490
  23:     0x7ff6fa1cfc97 - std::thread::local::LocalKey<core::cell::Cell<tokio_executor::global::State>>::with<core::cell::Cell<tokio_executor::global::State>,closure,core::result::Result<i32, futures::sync::oneshot::Canceled>>
                        at \rustc\00e03ee57446d47667e5adba77fca8c13bfe7535\src\libstd\thread\local.rs:255
  24:     0x7ff6fa1ce89a - std::thread::local::LocalKey<core::cell::RefCell<core::option::Option<tokio_timer::timer::handle::HandlePriv>>>::with<core::cell::RefCell<core::option::Option<tokio_timer::timer::handle::HandlePriv>>,closure,core::result::Result<i32, futures::sync::oneshot::Canceled>>
                        at \rustc\00e03ee57446d47667e5adba77fca8c13bfe7535\src\libstd\thread\local.rs:255
  25:     0x7ff6fa1cdd22 - std::thread::local::LocalKey<core::cell::Cell<core::option::Option<const tokio_timer::clock::clock::Clock*>>>::with<core::cell::Cell<core::option::Option<const tokio_timer::clock::clock::Clock*>>,closure,core::result::Result<i32, futures::sync::oneshot::Canceled>>
                        at \rustc\00e03ee57446d47667e5adba77fca8c13bfe7535\src\libstd\thread\local.rs:255
  26:     0x7ff6fa1ce326 - std::thread::local::LocalKey<core::cell::RefCell<core::option::Option<tokio_reactor::HandlePriv>>>::with<core::cell::RefCell<core::option::Option<tokio_reactor::HandlePriv>>,closure,core::result::Result<i32, futures::sync::oneshot::Canceled>>
                        at \rustc\00e03ee57446d47667e5adba77fca8c13bfe7535\src\libstd\thread\local.rs:255
  27:     0x7ff6fa1d3595 - tokio::runtime::current_thread::runtime::Runtime::block_on<futures::sync::oneshot::Receiver<i32>>
                        at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.1.11\src\runtime\current_thread\runtime.rs:185
  28:     0x7ff6fa1c13b3 - std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()>
                        at \rustc\00e03ee57446d47667e5adba77fca8c13bfe7535\src\libstd\sys_common\backtrace.rs:136
  29:     0x7ff6fa1c3299 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
                        at \rustc\00e03ee57446d47667e5adba77fca8c13bfe7535\src\libstd\panicking.rs:312
  30:     0x7ff6fa2f352c - panic_abort::__rust_maybe_catch_panic
                        at /rustc/00e03ee57446d47667e5adba77fca8c13bfe7535\/src\libpanic_abort\lib.rs:41
  31:     0x7ff6fa1b923f - alloc::boxed::{{impl}}::call_box<(),closure>
                        at \rustc\00e03ee57446d47667e5adba77fca8c13bfe7535\src\liballoc\boxed.rs:673
  32:     0x7ff6fa2f2165 - std::sys::windows::thread::{{impl}}::new::thread_start
                        at /rustc/00e03ee57446d47667e5adba77fca8c13bfe7535\/src\libstd\sys\windows\thread.rs:56
  33:     0x7fff3c3413d2 - BaseThreadInitThunk
thread 'arbiter:c6215fb3-e9ed-46bd-a4ee-b4d1dce0638a:actix-net-worker-0' panicked at 'Use Self::Context::notify() instead of direct use of address', C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-0.7.6\src\mailbox.rs:103:17
```

Why shouldn't it be allowed to send more than 256 messages at once? (I need to.)
