### ISSUE TITLE
Use Self::Context::notify() instead of direct use of address

### ISSUE THREAD

**Issue by daschl** [actix/actix#94]
Hi,

I'm new to actix so I don't know if this is a user error or not.

I have an actor system right now of 3 actors, one which does a blocking loop on a file reading it line by line and then two others that need to do processing in the future but for now are just forwarding.

Basic actor system setup:

```rust
    let system = System::new("oida");

    // Initialize the Parser
    let parser: Addr<Unsync, _> = Parser::new("^%{TIMESTAMP_ISO8601:timestamp} %{NUMBER:ign} \\| %{LOGLEVEL:level}%{SPACE} \\| %{GREEDYDATA:message}$").start();

    // Initialize the Line Aggregator Actor and start it in the current event loop
    let aggregator: Addr<Syn, _> = LineAggregator::new(parser.recipient()).start();
    let agg_recipient: Recipient<Syn, RawLineMessage> = aggregator.recipient();

    // Initialize the File Reader actor and send it to another thread since it
    // is using blocking api.
    SyncArbiter::start(1, move || {
        FileReader::new(agg_recipient.clone(), "tmp/input.log")
    });

    system.run();
```

Reader:

```rust
pub struct FileReader {
    recipient: Recipient<Syn, RawLineMessage>,
    path: String,
}

impl FileReader {
    pub fn new(recipient: Recipient<Syn, RawLineMessage>, path: &str) -> Self {
        FileReader {
            recipient,
            path: path.into(),
        }
    }
}

impl Actor for FileReader {
    type Context = SyncContext<Self>;

    fn started(&mut self, _: &mut Self::Context) {
        let file = File::open(&self.path).unwrap();
        let reader = BufReader::new(file);
        for line in reader.lines() {
            match self.recipient.do_send(RawLineMessage(line.unwrap())) {
                Ok(_) => (),
                Err(e) => println!("!!!! could not send log line {:?}", e),
            }
        }
    }
}
```

Aggregator:

```rust
pub struct LineAggregator {
    recipient: Recipient<Unsync, RawLineMessage>,
}

impl LineAggregator {
    pub fn new(recipient: Recipient<Unsync, RawLineMessage>) -> Self {
        LineAggregator { recipient }
    }
}

impl Actor for LineAggregator {
    type Context = Context<Self>;
}

impl Handler<RawLineMessage> for LineAggregator {
    type Result = ();

    fn handle(&mut self, msg: RawLineMessage, _: &mut Self::Context) {
        match self.recipient.do_send(msg) {
            Ok(_) => (),
            Err(e) => println!("!!!! could not send log line {:?}", e),
        }
    }
}
```

Finally the parser:

```rust
pub struct Parser {
    pattern: Pattern,
}

impl Parser {
    pub fn new(pattern: &str) -> Self {
        let mut grok = Grok::default();
        let compiled_pattern = grok.compile(pattern, false).unwrap();
        Parser {
            pattern: compiled_pattern,
        }
    }
}

impl Actor for Parser {
    type Context = Context<Self>;
}

impl Handler<RawLineMessage> for Parser {
    type Result = ();

    fn handle(&mut self, msg: RawLineMessage, _: &mut Self::Context) {
        println!("parser received: {:?}", msg);
    }
}
```

When I run this against a larger file with try_send I think it panics at the 16 item mailbox size (I know its configurable but why does it overflow?.. if I use the do_send as in the code here it fails with:

```
thread 'main' panicked at 'Use Self::Context::notify() instead of direct use of address',
```

```
thread 'main' panicked at 'Use Self::Context::notify() instead of direct use of address', /Users/daschl/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.5.8/src/mailbox.rs:134:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: std::panicking::begin_panic
             at libstd/panicking.rs:402
   5: std::panicking::begin_panic
             at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:365
   6: <actix::mailbox::Mailbox<A>>::poll
             at ./<panic macros>:3
   7: <actix::contextimpl::ContextImpl<A>>::poll
             at /Users/daschl/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.5.8/src/contextimpl.rs:291
   8: <actix::context::Context<A> as futures::future::Future>::poll
             at /Users/daschl/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.5.8/src/context.rs:144
   9: <futures::future::map::Map<A, F> as futures::future::Future>::poll
             at /Users/daschl/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/future/map.rs:30
  10: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll
             at /Users/daschl/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/future/map_err.rs:30
  11: <alloc::boxed::Box<F> as futures::future::Future>::poll
             at /Users/daschl/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/future/mod.rs:113
  12: <futures::task_impl::Spawn<T>>::poll_future_notify::{{closure}}
             at /Users/daschl/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/task_impl/mod.rs:289
  13: <futures::task_impl::Spawn<T>>::enter::{{closure}}
             at /Users/daschl/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/task_impl/mod.rs:363
  14: futures::task_impl::std::set
             at /Users/daschl/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/task_impl/std/mod.rs:78
  15: <futures::task_impl::Spawn<T>>::enter
             at /Users/daschl/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/task_impl/mod.rs:363
  16: <futures::task_impl::Spawn<T>>::poll_future_notify
             at /Users/daschl/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/task_impl/mod.rs:289
  17: <tokio::executor::current_thread::scheduler::Scheduled<'a, U>>::tick
             at /Users/daschl/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.7/src/executor/current_thread/scheduler.rs:352
  18: <tokio::executor::current_thread::scheduler::Scheduler<U>>::tick::{{closure}}
             at /Users/daschl/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.7/src/executor/current_thread/scheduler.rs:332
  19: <tokio::executor::current_thread::Borrow<'a, U>>::enter::{{closure}}::{{closure}}
             at /Users/daschl/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.7/src/executor/current_thread/mod.rs:762
  20: tokio::executor::current_thread::CurrentRunner::set_spawn
             at /Users/daschl/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.7/src/executor/current_thread/mod.rs:794
  21: <tokio::executor::current_thread::Borrow<'a, U>>::enter::{{closure}}
             at /Users/daschl/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.7/src/executor/current_thread/mod.rs:761
  22: <std::thread::local::LocalKey<T>>::try_with
             at /Users/travis/build/rust-lang/rust/src/libstd/thread/local.rs:290
  23: <std::thread::local::LocalKey<T>>::with
             at /Users/travis/build/rust-lang/rust/src/libstd/thread/local.rs:244
  24: <tokio::executor::current_thread::Borrow<'a, U>>::enter
             at /Users/daschl/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.7/src/executor/current_thread/mod.rs:760
  25: <tokio::executor::current_thread::scheduler::Scheduler<U>>::tick
             at /Users/daschl/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.7/src/executor/current_thread/scheduler.rs:332
  26: <tokio::executor::current_thread::Entered<'a, P>>::tick
             at /Users/daschl/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.7/src/executor/current_thread/mod.rs:611
  27: <tokio::executor::current_thread::Entered<'a, P>>::turn
             at /Users/daschl/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.7/src/executor/current_thread/mod.rs:537
  28: tokio_core::reactor::Core::poll::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at /Users/daschl/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.17/src/reactor/mod.rs:298
  29: <scoped_tls::ScopedKey<T>>::set
             at /Users/daschl/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.2/src/lib.rs:155
  30: tokio_core::reactor::Core::poll::{{closure}}::{{closure}}::{{closure}}
             at /Users/daschl/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.17/src/reactor/mod.rs:297
  31: tokio_timer::timer::handle::with_default::{{closure}}
             at /Users/daschl/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.4/src/timer/handle.rs:64
  32: <std::thread::local::LocalKey<T>>::try_with
             at /Users/travis/build/rust-lang/rust/src/libstd/thread/local.rs:290
  33: <std::thread::local::LocalKey<T>>::with
             at /Users/travis/build/rust-lang/rust/src/libstd/thread/local.rs:244
  34: tokio_timer::timer::handle::with_default
             at /Users/daschl/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.4/src/timer/handle.rs:56
  35: tokio_core::reactor::Core::poll::{{closure}}::{{closure}}
             at /Users/daschl/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.17/src/reactor/mod.rs:275
  36: tokio_executor::global::with_default::{{closure}}
             at /Users/daschl/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.2/src/global.rs:176
  37: <std::thread::local::LocalKey<T>>::try_with
             at /Users/travis/build/rust-lang/rust/src/libstd/thread/local.rs:290
  38: <std::thread::local::LocalKey<T>>::with
             at /Users/travis/build/rust-lang/rust/src/libstd/thread/local.rs:244
  39: tokio_executor::global::with_default
             at /Users/daschl/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.2/src/global.rs:150
  40: tokio_core::reactor::Core::poll::{{closure}}
             at /Users/daschl/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.17/src/reactor/mod.rs:274
  41: tokio_reactor::with_default::{{closure}}
             at /Users/daschl/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.2/src/lib.rs:231
  42: <std::thread::local::LocalKey<T>>::try_with
             at /Users/travis/build/rust-lang/rust/src/libstd/thread/local.rs:290
  43: <std::thread::local::LocalKey<T>>::with
             at /Users/travis/build/rust-lang/rust/src/libstd/thread/local.rs:244
  44: tokio_reactor::with_default
             at /Users/daschl/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.2/src/lib.rs:214
  45: <tokio_timer::timer::Timer<T, N> as tokio_executor::park::Park>::unpark
             at /Users/daschl/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.17/src/reactor/mod.rs:273
  46: tokio_core::reactor::Core::run
             at /Users/daschl/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.17/src/reactor/mod.rs:248
  47: <std::sync::mpsc::cache_aligned::CacheAligned<T> as core::ops::deref::Deref>::deref
             at /Users/daschl/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.5.8/src/system.rs:106
  48: oida::main
             at src/main.rs:37
  49: std::rt::lang_start::{{closure}}
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  50: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:306
  51: panic_unwind::dwarf::eh::read_encoded_pointer
             at libpanic_unwind/lib.rs:102
  52: <std::io::Write::write_fmt::Adaptor<'a, T> as core::fmt::Write>::write_str
             at libstd/panicking.rs:285
             at libstd/panic.rs:361
             at libstd/rt.rs:58
  53: std::rt::lang_start
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  54: oida::main
```

Any idea what caused this and/or how do I maintain proper mailbox hygiene since the file reader is I assume decoupled from the rest of the actors which run in one event loop?

Thanks,
Michael

**Comment by DoumanAsh** [comment]
I'll copy what I said in gitter.

You should not use such loops during actor start:
```rust
fn started(&mut self, _: &mut Self::Context) {
let file = File::open(&self.path).unwrap(); 
let reader = BufReader::new(file); 
for line in reader.lines() {
    match self.recipient.do_send(RawLineMessage(line.unwrap())) {
        Ok(_) => (),
        Err(e) => println!("!!!! could not send log line {:?}", e), }
     } 
}
````

Actor start is synchronous so you send all messages for each line at once
And they ain't gonna get handled until you exit `Actor::started`

**Comment by daschl** [comment]
@DoumanAsh thanks for the info - I'm going to close this for now since I guess its a user error at this point and will reopen if I stumble on something that looks suspicious. thanks again!

**Comment by Sythanis** [comment]
Hey sorry to bump a closed issue but I am just getting the same error. I made sure I do not have a loop in the started method as @DoumanAsh has mentioned, yet I still get the error.

Similar to the author of this issue I am a beginner when it comes to actix and I would appreciate any help.
A short explanation of my problem:  I have a UDP Socket Actor living in its own Arbiter. The Actor is listening to the socket and once receives a message it sends the data to processing actor.

```
pub struct SocketStream {
     stream: Addr<VisionStream>,
      device_ip: IpAddr,
     internal: UdpSocket,
 }   
impl Actor for SocketStream {
      type Context = Context<Self>;
      fn started(&mut self, _ctx: &mut Context<Self>) {
          self.connect_to_interface(); // Just sends a message a small message via UDP port for firewall issue
      }
  }
impl SocketStream {
      fn listen_to_stream(&mut self) {
          loop {
              let mut packet_buff = [0;6000];
              match self.internal.recv(&mut packet_buff) {
                  Ok(bytes_read) => self.stream.do_send(
                      VisionPacket((&packet_buff[..bytes_read]).to_vec())
                  ),
                  Err(e) => panic!("Stream sock error {}", e),
              }
          }
      }
}
  #[derive(Message)]
  pub struct StartSocket();
  impl Handler<StartSocket> for SocketStream {
      type Result = ();
      fn handle(&mut self, _start: StartSocket, _ctx: &mut Context<Self>) {
          self.listen_to_stream();
      }
  }
```

I don't start the listening loop within the started() function but in a handle of a new StartSocket() message that is sent from the processing actor.

Yet I still obtain the Self::Context::notify() instead of direct use of address panic. Am I missing something?

Tnx for the amazing work on Actix and any help you can provide!

**Comment by DoumanAsh** [comment]
To be honest it is not exactly clear what is going on in your code.
I don't know whtat is this `SocketStream::connect_to_interface` but to give you advise it is more desirable to convert incoming data from your UDP socket to stream that could be passed to Actor and handled like [that](https://actix.rs/actix/actix/prelude/trait.StreamHandler.html#method.add_stream)

You can hop in gitter chat(see README.md for link) and ask for help there

**Comment by Sythanis** [comment]
Okey @DoumanAsh tnx will have a look! Will join Gitter as well

**Comment by PlaneB** [comment]
I also get the same error and have no loops in started() at all. The project is unfortunately to large to post it here. Its an escaling push gossip via udp. all started functions are like this:

    fn started(&mut self, _ctx: &mut Self::Context) {
        println!("BlaBla started.");
    }

nothing more...
